export const GET_HOUSE_MAINT_RECORDS = 'GET_HOUSE_MAINT_RECORDS';
export const SET_HOUSE_MAINT_RECORDS = 'SET_HOUSE_MAINT_RECORDS';
export const FETCH_HOUSE_MAINT_IN_PROGRESS = 'FETCH_HOUSE_MAINT_IN_PROGRESS';