export const GET_HOUSE_MAINT_RECORDS = 'GET_HOUSE_MAINT_RECORDS';

export const SET_HOUSE_MAINT_RECORDS = 'SET_HOUSE_MAINT_RECORDS';
export const GET_HOUSE_MAINT_RECORDS_IN_PROGRESS = 'GET_HOUSE_MAINT_RECORDS_IN_PROGRESS';
export const GET_HOUSE_MAINT_RECORDS_FAILURE = 'GET_HOUSE_MAINT_RECORDS_IN_PROGRESS';

export const UPDATE_HOUSE_MAINT_IN_PROGRESS = 'UPDATE_HOUSE_MAINT_IN_PROGRESS';
export const UPDATE_HOUSE_MAINT_RECORD_SUCCESS = 'UPDATE_HOUSE_MAINT_RECORD_SUCCESS';
export const UPDATE_HOUSE_MAINT_RECORD_FAILURE = 'UPDATE_HOUSE_MAINT_RECORD_FAILURE';

export const UPDATE_SELECETED_FIELDS = 'UPDATE_SELECETED_FIELDS';

export const ADD_HOUSE_MAINT_IN_PROGRESS = 'ADD_HOUSE_MAINT_IN_PROGRESS';
export const ADD_HOUSE_MAINT_RECORD_SUCCESS = 'ADD_HOUSE_MAINT_RECORD_SUCCESS';
export const ADD_HOUSE_MAINT_RECORD_FAILURE = 'ADD_HOUSE_MAINT_RECORD_FAILURE';

export const DELETE_ALL_HOUSE_MAINT_IN_PROGRESS = 'DELETE_ALL_HOUSE_MAINT_IN_PROGRESS';
export const DELETE_ALL_HOUSE_MAINT_SUCCESS = 'DELETE_ALL_HOUSE_MAINT_SUCCESS';
export const DELETE_ALL_HOUSE_MAINT_FAILURE = 'DELETE_ALL_HOUSE_MAINT_FAILURE';

export const DELETE_SELECTED_HOUSE_MAINT_IN_PROGRESS = 'DELETE_SELECTED_HOUSE_MAINT_IN_PROGRESS';
export const DELETE_SELECTED_HOUSE_MAINT_SUCCESS = 'DELETE_SELECTED_HOUSE_MAINT_SUCCESS';
export const DELETE_SELECTED_HOUSE_MAINT_FAILURE = 'DELETE_SELECTED_HOUSE_MAINT_FAILURE';

export const SET_NOTIFICATION_SUCCESS = 'SET_NOTIFICATION_SUCCESS';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
export const SET_NOTIFICATION_ERROR = 'SET_NOTIFICATION_ERROR';
